package com.github.se.oncompanion.resources

// Like R, but C
object C {
  object Tag {
    const val main_screen_container = "main_screen_container"

    const val sign_in_screen = "sign_in_screen"
    const val google_sign_in_button = "google_sign_in_button"
    const val sign_in_loading = "sign_in_loading"
    const val onboarding_role_screen = "onboarding_role_screen"
    const val onboarding_role_patient = "onboarding_role_patient"
    const val onboarding_role_caregiver = "onboarding_role_caregiver"
    const val onboarding_continue_button = "onboarding_continue_button"
    const val onboarding_information_screen = "onboarding_information_screen"
    const val onboarding_first_name_field = "onboarding_first_name_field"
    const val onboarding_family_name_field = "onboarding_family_name_field"
    const val onboarding_save_button = "onboarding_save_button"
    const val onboarding_saving = "onboarding_saving"
    const val overview_screen = "overview_screen"
    const val overview_shortcut_symptoms = "overview_shortcut_symptoms"
    const val overview_shortcut_prescriptions = "overview_shortcut_prescriptions"
    const val overview_shortcut_close_circle = "overview_shortcut_close_circle"
    const val overview_shortcut_profile = "overview_shortcut_profile"
    const val overview_greeting = "overview_greeting"
    const val overview_date = "overview_date"
    const val overview_loading = "overview_loading"
    const val overview_error = "overview_error"
    const val overview_retry = "overview_retry"
    const val overview_next_appointment = "overview_next_appointment"
    const val overview_no_appointment = "overview_no_appointment"
    const val overview_see_planning = "overview_see_planning"
    const val overview_today_list = "overview_today_list"
    const val overview_today_empty = "overview_today_empty"
    const val overview_shortcuts = "overview_shortcuts"

    const val bottom_navigation_bar = "bottom_navigation_bar"
    const val bottom_navigation_tab_overview = "bottom_navigation_tab_overview"
    const val bottom_navigation_tab_planning = "bottom_navigation_tab_planning"
    const val bottom_navigation_tab_events = "bottom_navigation_tab_events"
    const val planning_screen = "planning_screen"
    const val events_screen = "events_screen"
    const val symptoms_screen = "symptoms_screen"
    const val prescriptions_screen = "prescriptions_screen"
    const val close_circle_screen = "close_circle_screen"
    const val profile_screen = "profile_screen"
    const val profile_back = "profile_back"
    const val profile_loading = "profile_loading"
    const val profile_signed_out = "profile_signed_out"
    const val profile_missing = "profile_missing"
    const val profile_error = "profile_error"
    const val profile_retry = "profile_retry"
    const val profile_header = "profile_header"
    const val profile_initial = "profile_initial"
    const val profile_name = "profile_name"
    const val profile_member_since = "profile_member_since"
    const val profile_information = "profile_information"
    const val profile_first_name = "profile_first_name"
    const val profile_family_name = "profile_family_name"
    const val profile_email = "profile_email"
    const val profile_cancer_type = "profile_cancer_type"
    const val cancer_type_field = "cancer_type_field"
    const val cancer_type_suggestions = "cancer_type_suggestions"
    const val cancer_type_suggestion = "cancer_type_suggestion"

    fun overviewTodayItem(itemId: String) = "overview_today_item_$itemId"

    // Close circle
    const val close_circle_back_button = "close_circle_back_button"
    const val close_circle_loading = "close_circle_loading"
    const val close_circle_empty = "close_circle_empty"
    const val close_circle_empty_add_button = "close_circle_empty_add_button"
    const val close_circle_error = "close_circle_error"
    const val close_circle_retry_button = "close_circle_retry_button"
    const val close_circle_member_list = "close_circle_member_list"
    const val close_circle_members_count = "close_circle_members_count"
    const val close_circle_add_member_fab = "close_circle_add_member_fab"

    fun close_circle_member(uid: String) = "close_circle_member_$uid"
  }
}
